Acme\UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        isActive:
            type: boolean
            nullable: false
            comment: ''
            column: is_active
    lifecycleCallbacks: {  }
